default_install_hook_types: [pre-commit, post-commit, commit-msg]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        exclude: (template|ci).*\.(json|yml|yaml)$
      - id: check-added-large-files
        stages: [pre-commit]
        args: [--maxkb=10000]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [pre-commit]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.11.1" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        exclude: .*\.(postcssrc|eslintrc).(js)
        args: ["--fix", "--config=/etc/eslint.config.js"]
        stages: [pre-commit]
        verbose: true
        additional_dependencies:
        -  eslint-config-prettier@9.1.0
        -  eslint-plugin-import@2.31.0
        -  eslint-plugin-node@11.1.0
        -  eslint-plugin-prettier@5.2.1
        -  eslint-plugin-promise@7.1.0
        -  prettier@3.3.3
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       description: 'ESLint'
  #       entry: npx eslint
  #       exclude: .*\.(postcssrc|eslintrc).(js)
  #       stages: [pre-commit]
  #       language: node
  #       'types': [javascript]
  #       args: ["--fix", "--config=/etc/eslint.config.js"]
  #       require_serial: false
  #       additional_dependencies: ["eslint@9.11.1"]
  #       minimum_pre_commit_version: '0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        stages: [pre-commit]
        always_run: true
        args: ["--print-width", "120"]
        exclude: >
          (?x)^(
              (.*)/static/vendors|
              (.*)/static/ico|
              ^.+\.html$|
              ^.+\.d.ts$|
              cdk.out\**$|
              package-lock.json|
              yarn.lock|
              CHANGELOG.md|
              (.*)\.vtl$|
              ^\*\\__test__\\\*\*\.test\.\*$|
              ^.+\.min\.(js|css)$
          )$
        additional_dependencies:
          - prettier@2.2.1

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [--exclude=templates/]
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        files: ^source/
        types: [file, python]
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: cdk-synth
        name: AWS CDK Synth
        entry: cdk synth --all
        language: system
        files: '^.+\.(py|ts|js|cs|fs|java)'
        pass_filenames: false
        stages: [pre-commit]
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.86.2 # The version of cfn-lint to use
    hooks:
      - id: cfn-lint-rc
        stages: [pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: 'v9.18.0'
    hooks:
      - id: commitlint
        name: Commitlint hook
        description: Commitlint hook
        stages: [commit-msg]
